### ISSUE TITLE
error when load the data

### ISSUE THREAD

**Issue by 1245244103** [Heidelberg-NLP/COINS#2]
I run the following script to load the data:
```
python scripts/data/make_conceptnet_data_loader.py
```
However,it reminded me "No such file or directory: 'data/conceptnet//train100k.txt'"
Then,i run the script as the instruction of the COMET:
```
bash scripts/setup/get_conceptnet_data.sh
```
Successfully,i got the **train100k.txt**.Then I run the script to load the data again. This time, another problem arose.
```
Traceback (most recent call last):
  File "scripts/data/make_conceptnet_data_loader.py", line 67, in <module>
    data_loader.load_data("data/conceptnet/")
  File "/data/yj/COINS-main/model/src/data/conceptnet.py", line 72, in load_data
    [(i[0].lower().strip(), i[1].lower().strip(), i[2].lower().strip(), i[3].lower().strip(), i[4].lower().strip(), i[5].lower().strip(), i[6].lower().strip(), i[7].lower().strip(), i[8].lower().strip(), i[9].lower().strip(), i[10].lower().strip()) for i in tuples]
  File "/data/yj/COINS-main/model/src/data/conceptnet.py", line 72, in <listcomp>
    [(i[0].lower().strip(), i[1].lower().strip(), i[2].lower().strip(), i[3].lower().strip(), i[4].lower().strip(), i[5].lower().strip(), i[6].lower().strip(), i[7].lower().strip(), i[8].lower().strip(), i[9].lower().strip(), i[10].lower().strip()) for i in tuples]
IndexError: list index out of range
```

**Comment by Li-Z-Q** [comment]
i met the same error

**Comment by 1754699523** [comment]
I met the same error,do you slove it?

**Comment by debjitpaul** [comment]
What is the format of the data?  Please check the baseline format: https://github.com/Heidelberg-NLP/COINS/tree/main/data/baseline
